apiVersion: v1
kind: Service
metadata:
  name: subjectservice
  labels:
    app: subjectservice
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: subjectservice
